app:
  schema-name: &schema-name processing_center_service
  cache:
    ttl-seconds: 600

retry:
  max-attempts: 3
  backoff: 100


keycloak:
  auth-server-url: http://keycloak:8080
  realm: bank-realm
  resource: processing-center-service  # Уникальное имя для каждого сервиса
  credentials:
    secret: QdIIM6rxhex4lPiXCyqm1An7cNgftAZq
  bearer-only: true  # Только проверка токенов
  jwks-url: http://keycloak:8080/realms/bank-realm/protocol/openid-connect/certs

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # 100% трассировок

opentelemetry:
  service:
    name: processing-center-service
  traces:
    exporter:
      type: jaeger
    jaeger:
      endpoint: http://jaeger:14250

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8001/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.meshakin: DEBUG
  file:
    name: logs/processing-center.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: redis_cache_payment_system
      port: 6379

  datasource:
    url: jdbc:postgresql://postgres_db_payment_system:5432/mydb?currentSchema=processing_center_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        default_schema: *schema-name # Используем якорь

  liquibase:
    change-log: classpath:/db/changelog/db/changelog-master.xml
    default-schema: *schema-name
    liquibase-schema: *schema-name
    parameters:
      schemaName: *schema-name # Один параметр для всех миграций
    contexts: dev # Контекст выполнения


  cache:
    type: redis
    redis:
      time-to-live: ${app.cache.ttl-seconds}s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operationsSorter: alpha
    tagsSorter: alpha